# Generated by Django 3.0.5 on 2021-10-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211028_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registrationDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Registration Date'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Username'),
        ),
    ]
