# Generated by Django 3.0.5 on 2021-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211028_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=None, max_length=240, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=None, max_length=240, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default='111111', max_length=10, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='111111', max_length=10, verbose_name='Password2'),
        ),
    ]
