# Generated by Django 3.0.5 on 2021-10-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211029_0823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
