# Generated by Django 3.0.5 on 2021-10-29 12:11

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='user')),
                ('address', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/Users/')),
                ('mobile', models.CharField(max_length=20)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
            ],
        ),
    ]
