# Generated by Django 3.0.5 on 2021-10-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211029_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registrationDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Registration Date'),
        ),
    ]
