# Generated by Django 3.0.5 on 2021-10-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_registrationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=240, verbose_name='First Name')),
                ('last_name', models.CharField(default=None, max_length=240, verbose_name='Last Name')),
                ('email', models.EmailField(default=None, max_length=254)),
                ('username', models.CharField(blank=True, max_length=240, null=True, verbose_name='Username')),
                ('password1', models.CharField(default='111111', max_length=10, verbose_name='Password')),
                ('password2', models.CharField(default='111111', max_length=10, verbose_name='Password2')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Customer'),
        ),
    ]
