# Generated by Django 3.0.5 on 2021-11-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211029_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='registrationDate',
        ),
        migrations.AddField(
            model_name='customer',
            name='registrationDate',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Registration Date'),
        ),
    ]
