# Generated by Django 3.0.5 on 2021-10-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
