# Generated by Django 3.2.9 on 2021-11-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0013_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
