# Generated by Django 3.2.9 on 2021-11-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0017_product_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image3',
            field=models.ImageField(blank=True, default='avatar-1.png', null=True, upload_to='featured_images'),
        ),
    ]
