# Generated by Django 4.0.1 on 2022-01-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0027_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
