# Generated by Django 4.0.1 on 2022-01-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0029_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Local', 'Local'), ('Contemporary', 'Contemporary'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Fruits', 'Fruits'), ('Drinks', 'Drinks'), ('Dinner', 'Dinner'), ('Soup', 'Soup'), ('Stews', 'Stews'), ('Snacks', 'Snacks'), ('Porridge', 'Porridge'), ('Sauce', 'Sauce')], default=None, max_length=255),
        ),
    ]
