# Generated by Django 4.0.1 on 2022-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0031_order_stripe_payment_intent_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='orderstatus',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
