# Generated by Django 4.0.1 on 2022-02-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0032_rename_status_order_orderstatus_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_payment_intent',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
