# Generated by Django 3.0.5 on 2021-11-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0004_auto_20211101_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[{'image': 'category_image/sm-7.jpg', 'name': 'Traditional'}], default=None, max_length=255),
        ),
    ]
