# Generated by Django 3.0.5 on 2021-11-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0005_auto_20211101_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Traditional', 'Traditional')], default=None, max_length=255),
        ),
    ]
