# Generated by Django 3.0.5 on 2021-11-01 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sage_main', '0006_auto_20211101_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Traditional', 'Traditional'), ('Contemporary', 'Contemporary'), ('Breakfast', 'Breakfast')], default=None, max_length=255),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(blank=True, default=None, null=True)),
                ('address', models.CharField(max_length=240)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('Ordered_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sage_main.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
