# Generated by Django 3.2.9 on 2021-11-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0007_auto_20211101_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Deleted Price'),
        ),
    ]
