# Generated by Django 3.2.9 on 2021-11-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0009_auto_20211103_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
