# Generated by Django 3.2.9 on 2021-11-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0012_alter_product_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
