# Generated by Django 3.2.9 on 2021-11-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0014_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Ordered_products',
            new_name='ordered_products',
        ),
    ]
