# Generated by Django 3.2.9 on 2021-12-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0020_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image1',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image2',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image3',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
