# Generated by Django 3.2.9 on 2021-12-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0023_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
