# Generated by Django 3.2.9 on 2021-12-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sage_main', '0025_auto_20211216_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sage_main.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Local', 'Local'), ('Contemporary', 'Contemporary'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Fruits', 'Fruits'), ('Drinks', 'Drinks'), ('Dinner', 'Dinner'), ('Soup', 'Soup'), ('Carbs', 'Carbs'), ('Stews', 'Stews'), ('Snacks', 'Snacks'), ('Porridge', 'Porridge')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sage_main.product'),
        ),
    ]
